### ISSUE TITLE
benchmarking rdtsc

### ISSUE THREAD

**Issue by tonyday567** [mgrabmueller/rdtsc#1]
Hi!

I'm getting very good numbers from benchmarking the cost of a rdtsc measurement - 40 cycles for both the c and hs code, so no ffi overhead whatsoever!

I wrote some benchmarks up here in case you're interested: https://github.com/tonyday567/perf

Sweet library :-)

**Comment by mgrabmueller** [comment]
Sounds great, thank you very much for trying it out! When I find the time, I will update the haddocks and .cabal descriptions with your findings.

**Comment by tonyday567** [comment]
Before I close this, is there any chance you could get this on stack?  I'd be happy to help with a PR (but have never tried before myself).

**Comment by mgrabmueller** [comment]
I would be happy to accept a PR, but I will probably not be able to look into it too deeply. Thanks.
